name = "bodwin-papers"
version = "0.1.0"
defaultTargets = ["VFTSpanners", "LinearDistancePreservers", "LightSpanners", "DegreeFaultSpanners"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "VFTSpanners"
srcDir = "A Trivial Yet Optimal Solution to Vertex Fault Tolerant Spanners"

[[lean_lib]]
name = "LinearDistancePreservers"
srcDir = "New Results on Linear Size Distance Preservers"

[[lean_lib]]
name = "LightSpanners"
srcDir = "An Alternate Proof of Near-Optimal Light Spanners"

[[lean_lib]]
name = "DegreeFaultSpanners"
srcDir = "Unconditional Lower Bounds for Degree Fault Tolerant Spanners"
