import DirectedFlowCutGap.EncodedCandidateCapacity

/-!
# Concrete retained enumeration for the candidate network

All lists below are generated by explicit recurrences. Bounded natural labels
are emitted in ascending order; sums preserve their left/right block order,
and products use their left factor as the outer loop. Each stage retains its
list and a Fintype dictionary wrapping that very list, without deduplication,
choice, or an arbitrary equivalence callback.

The word model charges list cases, allocations, tag and pair construction,
scalar addition and sequencing. Ghost counters and proofs are not charged.
Append copying is charged explicitly. Dictionary construction is a constant
number of wrappers around the retained list, not another universe traversal.
This is an algorithmic model, not a claim about Lean's compiler or allocator.
-/
set_option synthInstance.maxSize 4096

namespace DirectedFlowCutGap.CandidateEnumeration

open IntegralNetworkFlow CandidateGridOptimizer CandidateThresholdClosure

/-- A retained list and the finite dictionary sharing its exact contents. -/
structure Built (A : Type*) where
  enumeration : ResidualSearch.Enumeration A
  dictionary : Fintype A
  dictionary_matches : dictionary.elems.val = (enumeration.vertices : Multiset A)
  work : ℕ

theorem Built.dictionary_card {A : Type*} (a : Built A) :
    @Fintype.card A a.dictionary = a.enumeration.vertices.length := by
  change a.dictionary.elems.val.card = _
  rw [a.dictionary_matches]
  rfl

/-- Eight operations cover the enumeration, multiset/finset/dictionary and
result wrappers. All certificate fields are erased. -/
def pack {A : Type*} (xs : List A) (hn : xs.Nodup) (hc : ∀ a, a ∈ xs)
    (work : ℕ) : Built A :=
  { enumeration := ⟨xs,hn,hc⟩
    dictionary := ⟨⟨xs,hn⟩,hc⟩
    dictionary_matches := rfl
    work := work+8 }

@[simp] theorem pack_vertices {A : Type*} (xs : List A) (hn : xs.Nodup)
    (hc : ∀ a, a ∈ xs) (w : ℕ) : (pack xs hn hc w).enumeration.vertices = xs := rfl

/-- Ascending generation, with no quadratic remapping of an existing prefix.
The six operations are list case, scalar increment, recursion sequencing,
Fin wrapper, cons allocation and result allocation. -/
def finFrom (n k : ℕ) : (r : ℕ) → k+r ≤ n → List (Fin n) × ℕ
  | 0,_ => ([],1)
  | r+1,h =>
    let tail := finFrom n (k+1) r (by omega)
    (⟨k,by omega⟩::tail.1,tail.2+6)

theorem finFrom_length (n k r : ℕ) (h : k+r ≤ n) :
    (finFrom n k r h).1.length = r := by
  induction r generalizing k with
  | zero => rfl
  | succ r ih => simp [finFrom,ih]

theorem finFrom_work (n k r : ℕ) (h : k+r ≤ n) :
    (finFrom n k r h).2 = 6*r+1 := by
  induction r generalizing k with
  | zero => rfl
  | succ r ih => simp [finFrom,ih]; omega

theorem finFrom_mem (n k r : ℕ) (h : k+r ≤ n) (v : Fin n) :
    v ∈ (finFrom n k r h).1 ↔ k ≤ v.val ∧ v.val < k+r := by
  induction r generalizing k with
  | zero => simp [finFrom]
  | succ r ih =>
    simp only [finFrom,List.mem_cons,ih,Fin.ext_iff]
    omega

theorem finFrom_nodup (n k r : ℕ) (h : k+r ≤ n) :
    (finFrom n k r h).1.Nodup := by
  induction r generalizing k with
  | zero => simp [finFrom]
  | succ r ih =>
    simp only [finFrom,List.nodup_cons]
    exact ⟨by rw [finFrom_mem]; simp,ih _ _⟩

theorem finFrom_get (n k r : ℕ) (h : k+r ≤ n) (i : ℕ)
    (hi : i < (finFrom n k r h).1.length) :
    ((finFrom n k r h).1[i]).val = k+i := by
  induction r generalizing k i with
  | zero => simp [finFrom] at hi
  | succ r ih =>
    cases i with
    | zero => simp [finFrom]
    | succ i =>
      have ht : i < (finFrom n (k+1) r (by omega)).1.length := by
        simpa only [finFrom,List.length_cons,Nat.succ_lt_succ_iff] using hi
      simpa [finFrom,Nat.add_assoc,Nat.add_comm,Nat.add_left_comm] using ih (k+1) (by omega) i ht

def fin (n : ℕ) : Built (Fin n) :=
  let r := finFrom n 0 n (by omega)
  pack r.1 (finFrom_nodup n 0 n (by omega))
    (fun v => (finFrom_mem n 0 n (by omega) v).mpr (by omega)) r.2

@[simp] theorem fin_length (n : ℕ) : (fin n).enumeration.vertices.length = n :=
  finFrom_length n 0 n (by omega)

@[simp] theorem fin_work (n : ℕ) : (fin n).work = 6*n+9 := by
  simp [fin,pack,finFrom_work]

/-- Exact ascending list order, not just a permutation. -/
theorem fin_vertices (n : ℕ) : (fin n).enumeration.vertices = List.finRange n := by
  change (finFrom n 0 n (by omega)).1 = List.finRange n
  apply List.ext_getElem
  · simp only [finFrom_length,List.length_finRange]
  · intro i hi hj
    apply Fin.ext
    simpa only [List.getElem_finRange,Fin.val_cast,Nat.zero_add] using finFrom_get n 0 n (by omega) i hi

/-- The generated base list equals the existing explicit Fin enumeration. -/
theorem fin_order (n : ℕ) :
    (fin n).enumeration.vertices = (ResidualSearch.Enumeration.fin n).vertices := by
  rw [fin_vertices]
  rfl

def bool : Built Bool := pack [false,true] (by decide) (by intro b; cases b <;> simp) 9

@[simp] theorem bool_vertices : bool.enumeration.vertices = [false,true] := rfl
@[simp] theorem bool_work : bool.work = 17 := rfl

/-- Eight operations safely cover tag/list/result allocation and sequencing. -/
def leftTags {A B : Type*} : List A → List (A ⊕ B) × ℕ
  | [] => ([],1)
  | a::as => let r := leftTags as; (.inl a::r.1,r.2+8)

def rightTags {A B : Type*} : List B → List (A ⊕ B) × ℕ
  | [] => ([],1)
  | b::bs => let r := rightTags bs; (.inr b::r.1,r.2+8)

@[simp] theorem leftTags_value {A B : Type*} (xs : List A) :
    (leftTags (B := B) xs).1 = xs.map Sum.inl := by
  induction xs <;> simp [leftTags, *]

@[simp] theorem rightTags_value {A B : Type*} (xs : List B) :
    (rightTags (A := A) xs).1 = xs.map Sum.inr := by
  induction xs <;> simp [rightTags, *]

@[simp] theorem leftTags_work {A B : Type*} (xs : List A) :
    (leftTags (B := B) xs).2 = 8*xs.length+1 := by
  induction xs with
  | nil => rfl
  | cons x xs ih => simp only [leftTags,List.length_cons,ih]; omega

@[simp] theorem rightTags_work {A B : Type*} (xs : List B) :
    (rightTags (A := A) xs).2 = 8*xs.length+1 := by
  induction xs with
  | nil => rfl
  | cons x xs ih => simp only [rightTags,List.length_cons,ih]; omega

def sum {A B : Type*} (a : Built A) (b : Built B) : Built (A ⊕ B) :=
  let l := leftTags (B := B) a.enumeration.vertices
  let r := rightTags (A := A) b.enumeration.vertices
  pack (l.1++r.1) (by
    rw [leftTags_value,rightTags_value,List.nodup_append]
    refine ⟨a.enumeration.nodup.map (fun _ _ h => Sum.inl.inj h),
      b.enumeration.nodup.map (fun _ _ h => Sum.inr.inj h),?_⟩
    intro x hx y hy
    obtain ⟨x,_,rfl⟩ := List.mem_map.mp hx
    obtain ⟨y,_,rfl⟩ := List.mem_map.mp hy
    simp)
    (by
      intro x
      change x ∈ (leftTags a.enumeration.vertices).1 ++ (rightTags b.enumeration.vertices).1
      rw [leftTags_value,rightTags_value]
      cases x with
      | inl x =>
        exact List.mem_append_left _ (List.mem_map.mpr ⟨x,a.enumeration.complete x,rfl⟩)
      | inr x =>
        exact List.mem_append_right _ (List.mem_map.mpr ⟨x,b.enumeration.complete x,rfl⟩))
    (l.2+r.2+2*l.1.length+4)

@[simp] theorem sum_vertices {A B : Type*} (a : Built A) (b : Built B) :
    (sum a b).enumeration.vertices =
      a.enumeration.vertices.map Sum.inl ++ b.enumeration.vertices.map Sum.inr := by
  simp [sum]

@[simp] theorem sum_length {A B : Type*} (a : Built A) (b : Built B) :
    (sum a b).enumeration.vertices.length =
      a.enumeration.vertices.length+b.enumeration.vertices.length := by simp

@[simp] theorem sum_work {A B : Type*} (a : Built A) (b : Built B) :
    (sum a b).work = 10*a.enumeration.vertices.length+8*b.enumeration.vertices.length+14 := by
  simp [sum,pack]; omega

/-- The pair row traverses the retained second factor once. -/
def pairRow {A B : Type*} (a : A) : List B → List (A × B) × ℕ
  | [] => ([],1)
  | b::bs => let r := pairRow a bs; ((a,b)::r.1,r.2+8)

@[simp] theorem pairRow_value {A B : Type*} (a : A) (bs : List B) :
    (pairRow a bs).1 = bs.map fun b => (a,b) := by
  induction bs <;> simp [pairRow, *]

@[simp] theorem pairRow_work {A B : Type*} (a : A) (bs : List B) :
    (pairRow a bs).2 = 8*bs.length+1 := by
  induction bs with
  | nil => rfl
  | cons b bs ih => simp only [pairRow,List.length_cons,ih]; omega

/-- The first factor is the outer loop. The append copies every row and is
charged twice its length in addition to the explicit row construction. -/
def pairRows {A B : Type*} (bs : List B) : List A → List (A × B) × ℕ
  | [] => ([],1)
  | a::as =>
    let r := pairRow a bs
    let tail := pairRows bs as
    (r.1++tail.1,r.2+tail.2+2*r.1.length+4)

@[simp] theorem pairRows_value {A B : Type*} (as : List A) (bs : List B) :
    (pairRows bs as).1 = as.flatMap fun a => bs.map fun b => (a,b) := by
  induction as <;> simp [pairRows, *]

@[simp] theorem pairRows_work {A B : Type*} (as : List A) (bs : List B) :
    (pairRows bs as).2 = as.length*(10*bs.length+5)+1 := by
  induction as with
  | nil => simp [pairRows]
  | cons a as ih => simp only [pairRows,pairRow_work,pairRow_value,List.length_map,List.length_cons,ih,Nat.add_mul,Nat.one_mul]; omega

theorem pairRows_length {A B : Type*} (as : List A) (bs : List B) :
    (pairRows bs as).1.length = as.length*bs.length := by
  induction as <;> simp [pairRows, *,Nat.add_mul,Nat.add_comm]

theorem pairRows_nodup {A B : Type*} (as : List A) (bs : List B)
    (ha : as.Nodup) (hb : bs.Nodup) : (pairRows bs as).1.Nodup := by
  induction as with
  | nil => simp [pairRows]
  | cons a as ih =>
    have h := List.nodup_cons.mp ha
    simp only [pairRows,pairRow_value,List.nodup_append]
    refine ⟨hb.map (fun x y he => (Prod.mk.inj he).2),ih h.2,?_⟩
    intro x hx y hy he
    obtain ⟨b,_,rfl⟩ := List.mem_map.mp hx
    rw [pairRows_value] at hy
    obtain ⟨a',ha',hy⟩ := List.mem_flatMap.mp hy
    obtain ⟨b',_,he'⟩ := List.mem_map.mp hy
    cases he'
    exact h.1 ((Prod.mk.inj he).1.symm ▸ ha')

def prod {A B : Type*} (a : Built A) (b : Built B) : Built (A × B) :=
  let r := pairRows b.enumeration.vertices a.enumeration.vertices
  pack r.1 (pairRows_nodup _ _ a.enumeration.nodup b.enumeration.nodup)
    (by
      intro ⟨x,y⟩
      rw [pairRows_value]
      exact List.mem_flatMap.mpr ⟨x,a.enumeration.complete x,
        List.mem_map.mpr ⟨y,b.enumeration.complete y,rfl⟩⟩) r.2

@[simp] theorem prod_vertices {A B : Type*} (a : Built A) (b : Built B) :
    (prod a b).enumeration.vertices =
      a.enumeration.vertices.flatMap fun x => b.enumeration.vertices.map fun y => (x,y) := by
  simp [prod]

@[simp] theorem prod_length {A B : Type*} (a : Built A) (b : Built B) :
    (prod a b).enumeration.vertices.length =
      a.enumeration.vertices.length*b.enumeration.vertices.length :=
  pairRows_length _ _

@[simp] theorem prod_work {A B : Type*} (a : Built A) (b : Built B) :
    (prod a b).work = a.enumeration.vertices.length*(10*b.enumeration.vertices.length+5)+9 := by
  simp [prod,pack]

abbrev Port (n : ℕ) := TerminalPorts.Vertex (Fin n)
abbrev Point (n : ℕ) := CandidateGridOptimizer.Point (Fin n)
abbrev Node (n L : ℕ) := CandidateThresholdClosure.Node (Point n) L
abbrev Network (n L : ℕ) := MinimumClosureCut.Vertex (Node n L)

/-- Intermediate lists and dictionaries are retained as well as the public
EV/EP/EN/E lists. Each stage is computed once, and reused by reference. -/
structure Factory (n L : ℕ) where
  base : Built (Fin n)
  boolean : Built Bool
  twoPorts : Built (Fin n ⊕ Fin n)
  ports : Built (Port n)
  points : Built (Point n)
  levels : Built (Fin (L+1))
  nodes : Built (Node n L)
  network : Built (Network n L)
  work : ℕ

def make (n L : ℕ) : Factory n L :=
  let v := fin n
  let b := bool
  let t := sum v v
  let p := sum v t
  let q := prod p b
  let l := fin (L+1)
  let a := prod q l
  let e := sum a b
  ⟨v,b,t,p,q,l,a,e,v.work+b.work+t.work+p.work+q.work+l.work+a.work+e.work+10⟩

@[simp] theorem make_base_length (n L : ℕ) : (make n L).base.enumeration.vertices.length = n := by
  simp only [make,fin_length]
@[simp] theorem make_points_length (n L : ℕ) : (make n L).points.enumeration.vertices.length = 6*n := by
  simp only [make,prod_length,sum_length,fin_length,bool_vertices,List.length_cons,List.length_nil]
  omega
@[simp] theorem make_nodes_length (n L : ℕ) :
    (make n L).nodes.enumeration.vertices.length = 6*n*(L+1) := by
  simp only [make,prod_length,sum_length,fin_length,bool_vertices,List.length_cons,List.length_nil]
  ring
@[simp] theorem make_network_length (n L : ℕ) :
    (make n L).network.enumeration.vertices.length = 6*n*(L+1)+2 := by
  simp only [make,prod_length,sum_length,fin_length,bool_vertices,List.length_cons,List.length_nil]
  ring

/-- The full exact deterministic order used by finiteHooks: core, source,
sink blocks, false then true, ascending level, network source then sink. -/
def networkOrder (n L : ℕ) : List (Network n L) :=
  let vs := List.finRange n
  let ps : List (Port n) := vs.map Sum.inl ++
    (vs.map Sum.inl ++ vs.map Sum.inr).map Sum.inr
  let qs := ps.flatMap fun p => [false,true].map fun b => (p,b)
  let ns := qs.flatMap fun p => (List.finRange (L+1)).map fun l => (p,l)
  ns.map Sum.inl ++ [.inr false,.inr true]

theorem make_network_order (n L : ℕ) :
    (make n L).network.enumeration.vertices = networkOrder n L := by
  simp only [make,sum_vertices,prod_vertices,fin_vertices,bool_vertices,networkOrder,List.map_cons,List.map_nil]

/-- Exact construction charge, including dictionary and retained-record
wrappers. This theorem follows the executed recurrence, not a callback bound. -/
theorem make_work (n L : ℕ) :
    (make n L).work = 120*n*(L+1)+155*n+6*L+127 := by
  simp only [make,fin_work,bool_work,sum_work,prod_work,prod_length,sum_length,fin_length,
    bool_vertices,List.length_cons,List.length_nil]
  ring

/-- Empty inputs retain a level list, so the general bound exposes L. A
candidate call has s : Fin n and hence n>0; its stronger N-bound is below. -/
theorem make_general_bound (n L : ℕ) :
    (make n L).work ≤ 200*(n+L+(6*n*(L+1)+2)+1) := by
  rw [make_work]
  nlinarith

theorem make_network_bound (n L : ℕ) (hn : 0<n) :
    (make n L).work ≤ 60*(6*n*(L+1)+3) := by
  rw [make_work]
  have h₁ : n ≤ n*(L+1) := by
    simpa using Nat.mul_le_mul_left n (show 1≤L+1 by omega)
  have h₂ : L ≤ n*(L+1) := by
    have h := Nat.mul_le_mul_right (L+1) (show 1≤n by omega)
    simp only [Nat.one_mul] at h
    omega
  nlinarith

/-- Direct scalar indexing has fixed tag depth and no table search. -/
def portIndex {n : ℕ} : Port n → ℕ
  | .inl v => v.val
  | .inr (.inl v) => n+v.val
  | .inr (.inr v) => 2*n+v.val

def pointIndex {n : ℕ} (p : Point n) : ℕ := 2*portIndex p.1 + if p.2 then 1 else 0

def nodeIndex {n L : ℕ} (p : Node n L) : ℕ := pointIndex p.1*(L+1)+p.2.val

def networkIndex {n L : ℕ} : Network n L → ℕ
  | .inl p => nodeIndex p
  | .inr b => 6*n*(L+1) + if b then 1 else 0

theorem portIndex_lt {n : ℕ} (p : Port n) : portIndex p < 3*n := by
  cases p with
  | inl v => have h := v.isLt; simp only [portIndex]; omega
  | inr p => cases p <;> rename_i v <;> have h := v.isLt <;> simp only [portIndex] <;> omega

theorem pointIndex_lt {n : ℕ} (p : Point n) : pointIndex p < 6*n := by
  have h := portIndex_lt p.1
  unfold pointIndex
  split <;> omega

theorem nodeIndex_lt {n L : ℕ} (p : Node n L) : nodeIndex p < 6*n*(L+1) := by
  have hp := pointIndex_lt p.1
  have hl := p.2.isLt
  have hm := Nat.mul_le_mul_right (L+1) (show pointIndex p.1+1 ≤ 6*n by omega)
  unfold nodeIndex
  nlinarith

theorem networkIndex_lt {n L : ℕ} (p : Network n L) : networkIndex p < 6*n*(L+1)+2 := by
  cases p with
  | inl p => exact (nodeIndex_lt p).trans (by omega)
  | inr b => cases b <;> simp [networkIndex]

/-- Direct indices uniquely encode all fixed-depth sum/product labels. -/
theorem portIndex_injective {n : ℕ} : Function.Injective (@portIndex n) := by
  intro a b h
  rcases a with a | a | a <;> rcases b with b | b | b <;>
    have ha := a.isLt <;> have hb := b.isLt <;>
    simp_all [portIndex,Fin.ext_iff] <;> omega

theorem pointIndex_injective {n : ℕ} : Function.Injective (@pointIndex n) := by
  rintro ⟨a,x⟩ ⟨b,y⟩ h
  cases x <;> cases y <;> simp only [pointIndex,Bool.false_eq_true,ite_false,ite_true] at h
  · have he : portIndex a = portIndex b := by omega
    exact congrArg (fun p => (p,false)) (portIndex_injective he)
  · omega
  · omega
  · have he : portIndex a = portIndex b := by omega
    exact congrArg (fun p => (p,true)) (portIndex_injective he)

theorem nodeIndex_injective {n L : ℕ} : Function.Injective (@nodeIndex n L) := by
  intro a b h
  have hl : a.2.val = b.2.val := by
    have hh := congrArg (fun k => k % (L+1)) h
    simpa [nodeIndex,Nat.add_mod,Nat.mod_eq_of_lt a.2.isLt,Nat.mod_eq_of_lt b.2.isLt] using hh
  have hp : pointIndex a.1 = pointIndex b.1 := by
    apply Nat.mul_right_cancel (show 0<L+1 by omega)
    exact Nat.add_right_cancel (by simpa only [nodeIndex,hl] using h)
  exact Prod.ext (pointIndex_injective hp) (Fin.ext hl)

theorem networkIndex_injective {n L : ℕ} : Function.Injective (@networkIndex n L) := by
  intro a b h
  cases a with
  | inl a =>
    cases b with
    | inl b => exact congrArg Sum.inl (nodeIndex_injective h)
    | inr b =>
      have ha := nodeIndex_lt a
      cases b <;> simp only [networkIndex,ite_true,ite_false,Bool.false_eq_true] at h <;> omega
  | inr a =>
    cases b with
    | inl b =>
      have hb := nodeIndex_lt b
      cases a <;> simp only [networkIndex,ite_true,ite_false,Bool.false_eq_true] at h <;> omega
    | inr b => cases a <;> cases b <;> simp_all [networkIndex]

/-- Binary width of products is at most the sum of operand widths. -/
theorem size_mul_le (a b : ℕ) : Nat.size (a*b) ≤ Nat.size a+Nat.size b := by
  apply Nat.size_le.mpr
  rw [pow_add]
  exact Nat.mul_lt_mul_of_lt_of_le (Nat.lt_size_self a)
    (Nat.le_of_lt (Nat.lt_size_self b)) (by positivity)

/-- Label scalars, the ascending counters and direct network indices fit a
word whose size is linear in the two binary input lengths. -/
def labelBits (n L : ℕ) : ℕ := Nat.size n+Nat.size L+10

theorem network_size_bound (n L : ℕ) : Nat.size (6*n*(L+1)+2) ≤ labelBits n L := by
  have h₁ := EncodedCandidateCapacity.Input.size_add_le L 1
  have h₂ := size_mul_le 6 n
  have h₃ := size_mul_le (6*n) (L+1)
  have h₄ := EncodedCandidateCapacity.Input.size_add_le (6*n*(L+1)) 2
  rw [show Nat.size 6 = 3 by decide] at h₂
  rw [show Nat.size 2 = 2 by decide] at h₄
  simp only [Nat.size_one] at h₁
  unfold labelBits
  omega

theorem networkIndex_bits {n L : ℕ} (p : Network n L) :
    Nat.size (networkIndex p) ≤ labelBits n L :=
  (Nat.size_le_size (Nat.le_of_lt (networkIndex_lt p))).trans (network_size_bound n L)

theorem base_scalar_bits {n : ℕ} (v : Fin n) (L : ℕ) : Nat.size v.val ≤ labelBits n L := by
  have h := Nat.size_le_size (Nat.le_of_lt v.isLt)
  unfold labelBits
  omega

theorem level_scalar_bits {L : ℕ} (v : Fin (L+1)) (n : ℕ) : Nat.size v.val ≤ labelBits n L := by
  have h := Nat.size_le_size (Nat.le_of_lt_succ v.isLt)
  unfold labelBits
  omega

/-- The dictionary retains the same finite list, with no deduplication pass. -/
theorem pack_dictionary {A : Type*} (xs : List A) (hn : xs.Nodup)
    (hc : ∀ a, a ∈ xs) (w : ℕ) :
    (pack xs hn hc w).dictionary.elems.val = (xs : Multiset A) := rfl

theorem make_dictionary (n L : ℕ) :
    (make n L).network.dictionary.elems.val =
      ((make n L).network.enumeration.vertices : Multiset (Network n L)) := rfl

theorem make_dictionary_card (n L : ℕ) :
    @Fintype.card (Network n L) (make n L).network.dictionary = 6*n*(L+1)+2 := by
  change (make n L).network.dictionary.elems.val.card = _
  rw [make_dictionary]
  exact make_network_length n L

/-- Counter bounds apply at every recursive call of the bounded generator. -/
theorem finFrom_counter_bits (n k r : ℕ) (h : k+r≤n) (L : ℕ) :
    Nat.size k ≤ labelBits n L ∧ Nat.size r ≤ labelBits n L := by
  have hk := Nat.size_le_size (show k≤n by omega)
  have hr := Nat.size_le_size (show r≤n by omega)
  unfold labelBits
  omega

/-- The counted direct index uses only fixed-depth tags and scalar arithmetic. -/
def portIndexWithCost {n : ℕ} : Port n → ℕ × ℕ
  | .inl v => (v.val,2)
  | .inr (.inl v) => (n+v.val,4)
  | .inr (.inr v) => (2*n+v.val,5)

def networkIndexWithCost {n L : ℕ} : Network n L → ℕ × ℕ
  | .inl p =>
    let i := portIndexWithCost p.1.1
    let j := 2*i.1 + if p.1.2 then 1 else 0
    (j*(L+1)+p.2.val,i.2+10)
  | .inr b => (6*n*(L+1)+(if b then 1 else 0),8)

theorem portIndexWithCost_value {n : ℕ} (p : Port n) :
    (portIndexWithCost p).1 = portIndex p := by
  cases p with
  | inl v => rfl
  | inr p => cases p <;> rfl

theorem portIndexWithCost_bound {n : ℕ} (p : Port n) :
    (portIndexWithCost p).2 ≤ 5 := by
  cases p with
  | inl v => simp [portIndexWithCost]
  | inr p => cases p <;> simp [portIndexWithCost]

theorem networkIndexWithCost_value {n L : ℕ} (p : Network n L) :
    (networkIndexWithCost p).1 = networkIndex p := by
  cases p with
  | inl p => simp [networkIndexWithCost,networkIndex,nodeIndex,pointIndex,portIndexWithCost_value]
  | inr b => rfl

theorem networkIndexWithCost_bound {n L : ℕ} (p : Network n L) :
    (networkIndexWithCost p).2 ≤ 15 := by
  cases p with
  | inl p =>
    have h := portIndexWithCost_bound p.1.1
    simp only [networkIndexWithCost]
    omega
  | inr b => simp [networkIndexWithCost]

end DirectedFlowCutGap.CandidateEnumeration
